"""Report writers — findings.json + audit_report.md.

JSON is machine-readable / Splunk-ingestible. Markdown is the analyst /
GRC-reviewer artifact, organized by document, with an executive summary,
severity rollups, OWASP/AI-RMF category tables, and per-finding details.
"""

from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


SEVERITY_ORDER = {"critical": 0, "high": 1, "medium": 2, "low": 3}


def write_reports(
    *,
    findings: list[dict[str, Any]],
    summary: dict[str, Any],
    corpus_root: Path,
    out_dir: Path,
) -> None:
    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    run_meta = {
        "run_time": datetime.now(timezone.utc).isoformat(),
        "corpus_root": str(corpus_root),
        "summary": summary,
    }

    json_path = out_dir / "findings.json"
    with json_path.open("w", encoding="utf-8") as f:
        json.dump({"run": run_meta, "findings": findings}, f, indent=2)

    md_path = out_dir / "audit_report.md"
    with md_path.open("w", encoding="utf-8") as f:
        f.write(_render_markdown(findings=findings, run_meta=run_meta))


def _render_markdown(*, findings: list[dict[str, Any]], run_meta: dict[str, Any]) -> str:
    summary = run_meta["summary"]
    lines: list[str] = []

    lines.append("# RAG Pipeline Security Audit — Corpus Findings")
    lines.append("")
    lines.append(f"**Corpus:** `{run_meta['corpus_root']}`  ")
    lines.append(f"**Run time:** {run_meta['run_time']}  ")
    lines.append(f"**Documents scanned:** {summary['n_documents']}  ")
    lines.append(f"**Findings:** {summary['n_findings']}")
    lines.append("")

    lines.append("## Severity rollup")
    lines.append("")
    sev = summary["by_severity"]
    lines.append("| Critical | High | Medium | Low |")
    lines.append("|---:|---:|---:|---:|")
    lines.append(
        f"| {sev.get('critical', 0)} | {sev.get('high', 0)} "
        f"| {sev.get('medium', 0)} | {sev.get('low', 0)} |"
    )
    lines.append("")

    lines.append("## Executive summary")
    lines.append("")
    lines.append(_executive_summary(summary))
    lines.append("")

    lines.append("## Findings by category")
    lines.append("")
    lines.append("| Category | Count |")
    lines.append("|---|---:|")
    for cat, count in sorted(summary["by_category"].items()):
        lines.append(f"| {cat} | {count} |")
    lines.append("")

    lines.append("## Findings by document")
    lines.append("")
    lines.append("| Document | Findings |")
    lines.append("|---|---:|")
    for doc, count in sorted(summary["by_document"].items(), key=lambda x: -x[1]):
        lines.append(f"| `{doc}` | {count} |")
    lines.append("")

    lines.append("## OWASP LLM Top 10 (2025) coverage")
    lines.append("")
    lines.append("| OWASP category | Findings |")
    lines.append("|---|---:|")
    for cat, count in sorted(summary["by_owasp"].items()):
        lines.append(f"| {cat or '(unmapped)'} | {count} |")
    lines.append("")

    lines.append("## NIST AI RMF 1.0 evidence (keyed by subcategory)")
    lines.append("")
    lines.append(
        "Each corpus finding contributes evidence to one AI RMF subcategory. "
        "Findings indicate gaps a corpus-ingestion control would close before "
        "documents reach a production RAG retrieval layer."
    )
    lines.append("")
    lines.append("| AI RMF subcategory | Findings |")
    lines.append("|---|---:|")
    for sub, count in sorted(summary["by_airmf"].items()):
        lines.append(f"| {sub or '(unmapped)'} | {count} |")
    lines.append("")

    # Detailed findings, severity-sorted.
    sorted_findings = sorted(
        findings,
        key=lambda f: (SEVERITY_ORDER.get(f["severity"], 9), f["document_path"], f.get("line_number") or 0),
    )

    lines.append("## Detailed findings")
    lines.append("")
    for f in sorted_findings:
        lines.append(_render_finding(f))
        lines.append("")

    lines.append("---")
    lines.append("")
    lines.append(
        "*Generated by the RAG Pipeline Security Auditor — Project 3 of "
        "the AI Security Portfolio.*"
    )
    return "\n".join(lines) + "\n"


def _executive_summary(summary: dict[str, Any]) -> str:
    sev = summary["by_severity"]
    crit = sev.get("critical", 0)
    high = sev.get("high", 0)
    medium = sev.get("medium", 0)
    n = summary["n_findings"]
    if n == 0:
        return (
            "_No findings — corpus passes all four scanner classes. Recommend "
            "continued monitoring as the corpus evolves and as new scanner "
            "categories are added._"
        )
    parts: list[str] = []
    if crit:
        parts.append(
            f"**{crit}** critical finding(s) — typically credential leaks, classified "
            "spillage, or PEM-block private keys in corpus content. Block ingestion; "
            "rotate credentials; remove documents."
        )
    if high:
        parts.append(
            f"**{high}** high-severity finding(s) — high-severity PII leaks, sensitivity "
            "markers, or indirect-injection payloads. Quarantine documents pending review."
        )
    if medium:
        parts.append(
            f"**{medium}** medium-severity finding(s) — typically email-only PII or "
            "softer sensitivity markers. Consider redaction at ingestion."
        )
    return "\n\n".join(parts)


def _render_finding(f: dict[str, Any]) -> str:
    block: list[str] = []
    block.append(f"### [{f['severity'].upper()}] `{f['finding_id']}` — {f['title']}")
    block.append("")
    line_ref = f"L{f['line_number']}" if f.get("line_number") else "—"
    block.append(
        f"- **Document:** `{f['document_path']}` (line {line_ref})  · "
        f"**Scanner:** {f['scanner']}  · "
        f"**Category:** {f['category']}"
    )
    block.append(
        f"- **OWASP:** {f['owasp_category'] or '—'}  · "
        f"**ATLAS:** {', '.join(f['atlas_techniques']) or '—'}  · "
        f"**AI RMF:** {f['airmf_subcategory'] or '—'}"
    )
    block.append(f"- **Rationale:** {f['rationale']}")
    block.append("")
    block.append("**Excerpt:**")
    block.append("")
    block.append("```")
    block.append((f.get("excerpt") or "(empty)").strip())
    block.append("```")
    return "\n".join(block)
