"""Offline stub client — returns a deterministic brief built from the
bundle's actual STIX objects.

Used when no ANTHROPIC_API_KEY is available (CI, local dev without
keys, or `--offline` mode). The stub assembles a brief from real
bundle objects, so the citation verifier can still exercise its full
positive path. It does NOT hallucinate — its citations are by
construction valid — which means it doesn't exercise the verifier's
negative path. That negative path is exercised by the test suite,
which feeds hand-crafted briefs containing fake IDs.
"""

from __future__ import annotations

from feed.stix_types import StixBundle


class StubClient:
    """Drop-in replacement for the Anthropic SDK in offline mode."""

    name = "stub"

    def generate_brief(self, bundle: StixBundle) -> str:
        """Build a small, deterministic markdown brief from the bundle."""
        title = self._derive_title(bundle)
        lines: list[str] = []
        lines.append(f"# Threat Intel Brief — {title}")
        lines.append("")
        lines.append(f"**Source bundle:** `{bundle.bundle_id}`  ")
        lines.append(f"**STIX version:** {bundle.spec_version}  ")
        lines.append(f"**Objects in bundle:** {len(bundle)}")
        lines.append("")

        # Executive summary
        lines.append("## Executive summary")
        lines.append("")
        campaigns = bundle.by_type("campaign")
        actors = bundle.by_type("threat-actor")
        vulns = bundle.by_type("vulnerability")
        if campaigns:
            for c in campaigns:
                lines.append(
                    f"The bundle describes {c.name} [{c.id}]. "
                    f"{c.description}"
                )
        if actors:
            for a in actors:
                lines.append("")
                lines.append(
                    f"The campaign is attributed to {a.name} [{a.id}] — "
                    f"{a.description}"
                )
        if vulns:
            for v in vulns:
                lines.append("")
                lines.append(
                    f"The bundle covers {v.name} [{v.id}]: {v.description}"
                )
        lines.append("")

        # Indicators
        indicators = bundle.by_type("indicator")
        if indicators:
            lines.append("## Indicators of compromise")
            lines.append("")
            for ind in indicators:
                pattern = ind.raw.get("pattern", "")
                lines.append(f"- **{ind.name}** [{ind.id}] — {pattern}")
            lines.append("")

        # Attack patterns
        patterns = bundle.by_type("attack-pattern")
        if patterns:
            lines.append("## TTPs (MITRE ATT&CK)")
            lines.append("")
            for p in patterns:
                ext = p.raw.get("external_references", []) or []
                attck = next(
                    (e.get("external_id") for e in ext
                     if e.get("source_name") == "mitre-attack"),
                    "",
                )
                lines.append(f"- **{p.name}** [{p.id}]" + (f" — {attck}" if attck else ""))
            lines.append("")

        # Recommended actions — use any course-of-action plus generic guidance.
        actions = bundle.by_type("course-of-action")
        if actions or indicators:
            lines.append("## Recommended actions")
            lines.append("")
            for a in actions:
                lines.append(f"- {a.name} [{a.id}] — {a.description}")
            if indicators:
                ids = ", ".join(f"[{i.id}]" for i in indicators)
                lines.append(
                    f"- Block listed indicators at the perimeter: {ids}"
                )
            lines.append("")

        lines.append("---")
        lines.append("")
        lines.append(
            "*Generated by the offline stub client. Every citation in this "
            "brief is bound to a real object ID in the source bundle — the "
            "citation verifier should report zero hallucinations.*"
        )

        return "\n".join(lines) + "\n"

    def _derive_title(self, bundle: StixBundle) -> str:
        for c in bundle.by_type("campaign"):
            return c.name
        for v in bundle.by_type("vulnerability"):
            return v.name
        return bundle.bundle_id
