"""NVIDIA Morpheus pipeline-stage generator.

Morpheus is NVIDIA's GPU-accelerated cybersecurity AI framework. It
streams JSON events through a configurable stage chain (source →
deserialize → filter → monitor → aggregate → classify → serialize →
sink) and runs the pipeline on CUDA-enabled hardware. Each canonical
rule from the template library becomes one Morpheus pipeline whose
filter stage encodes the rule's condition and whose aggregate stage
encodes the rule's grouping + threshold.

Output is a YAML pipeline config, idiomatic for Morpheus deployments
that load pipelines from config files. The stage list is canonical —
in a production Morpheus deployment a runner script translates each
stage entry into the equivalent ``pipeline.add_stage(...)`` Python
call. The filter conditions use cuDF-compatible boolean expressions
so the same condition runs on the GPU dataframe path that Morpheus's
filter stage expects.

This generator is deploy-target-only — the pipeline configs are
shipped as artifacts; a Morpheus runtime (CUDA + GPU) executes them.
The generator itself runs on any platform since it only emits text.
"""

from __future__ import annotations

from .base import Condition, Rule


_SEVERITY_TO_MORPHEUS = {
    "low": "low",
    "medium": "medium",
    "high": "high",
    "critical": "critical",
}


class MorpheusGenerator:
    """Render a Rule as an NVIDIA Morpheus pipeline-stage YAML config."""

    name = "morpheus"
    output_subdir = "morpheus"
    file_extension = ".yaml"

    def filename(self, rule: Rule) -> str:
        return rule.id

    def render(self, rule: Rule) -> str:
        # Metadata header — Morpheus YAML supports comments. Mirror the
        # Cortex XSIAM header pattern so a reviewer sees the rule's
        # OWASP / ATLAS / AI RMF mapping at the top of the file.
        header = (
            f"# rule_id: {rule.id}\n"
            f"# name: {rule.name}\n"
            f"# severity: {rule.severity}\n"
            f"# owasp: {rule.owasp_llm}\n"
            f"# atlas: {', '.join(rule.mitre_atlas) or '(none)'}\n"
            f"# airmf: {rule.airmf}\n"
            f"# description: {rule.description.replace(chr(10), ' ')}\n"
            f"#\n"
            f"# Generated by Project 4 SIEM Correlation Generator. Drop into a\n"
            f"# Morpheus deployment under config/pipelines/. The stage list is\n"
            f"# canonical — translate each entry into pipeline.add_stage(...)\n"
            f"# calls in your runner script. Filter conditions are cuDF-\n"
            f"# compatible boolean expressions evaluated on the GPU dataframe.\n"
        )

        # Filter condition — combines the rule's source-event match
        # (cim_eventtype) with the rule's specific condition. Morpheus's
        # filter stage operates on the deserialized PAYLOAD dataframe, so
        # the expression syntax matches cuDF / pandas.
        filter_expr = (
            f'cim_eventtype == "{rule.event_type}" and '
            f"{_morpheus_condition(rule.condition)}"
        )

        # Aggregation — Morpheus has windowing primitives in
        # morpheus.stages.general.window_stage. We emit a structured
        # aggregate entry that the runner translates into the right
        # WindowStage / GroupByStage configuration.
        agg = rule.aggregation
        group_by_yaml = _yaml_inline_list(list(agg.group_by)) or "[]"
        window_seconds = _window_to_seconds(agg.window)

        # Tags — surfaced at the top level so downstream Morpheus tooling
        # (the optional metrics-export stage) can dimension alerts by
        # OWASP / ATLAS / AI RMF without re-parsing the rule body.
        atlas_yaml = _yaml_inline_list(list(rule.mitre_atlas)) or "[]"

        # Drilldown field is optional — emit a clean placeholder when missing
        # so the YAML stays well-formed.
        drilldown = rule.response.drilldown_field or "(none)"

        body = f"""\
pipeline:
  name: ai-security-{rule.id.lower()}
  feature_length: 256
  num_threads: 4
  pipeline_batch_size: 1024
  edge_buffer_size: 128

  source:
    type: from-kafka
    bootstrap_servers: ${{KAFKA_BOOTSTRAP_SERVERS}}
    input_topic: aisec-events
    group_id: morpheus-{rule.id.lower()}

  stages:
    - type: deserialize

    - type: monitor
      description: "Source — incoming aisec events"

    - type: filter
      filter_source: PAYLOAD
      condition: '{filter_expr}'

    - type: monitor
      description: "Matches — {rule.id} condition fired"

    - type: aggregate
      group_by: {group_by_yaml}
      threshold_count: {agg.threshold_count}
      window_seconds: {window_seconds}

    - type: add-class
      class_name: notable_event
      severity: {_SEVERITY_TO_MORPHEUS.get(rule.severity, "medium")}
      drilldown_field: {drilldown}
      rule_id: {rule.id}

    - type: serialize

  sink:
    type: to-kafka
    bootstrap_servers: ${{KAFKA_BOOTSTRAP_SERVERS}}
    output_topic: aisec-notables

tags:
  rule_id: {rule.id}
  owasp_llm: {rule.owasp_llm}
  mitre_atlas: {atlas_yaml}
  airmf: {rule.airmf}
  source_index: {rule.source_index}
  sourcetype: "{rule.sourcetype}"
"""

        return header + "\n" + body


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _morpheus_condition(c: Condition) -> str:
    """Translate a canonical Condition into a cuDF-compatible boolean expr.

    Morpheus's filter stage accepts pandas/cuDF-style expressions evaluated
    on the deserialized PAYLOAD dataframe.
    """
    field = c.field
    op = c.operator.lower()
    val = c.value
    if op == "equals":
        return f'{field} == {_morpheus_value(val)}'
    if op == "in":
        if isinstance(val, (list, tuple)):
            quoted = ", ".join(_morpheus_value(v) for v in val)
            return f"{field}.isin([{quoted}])"
        return f"{field} == {_morpheus_value(val)}"
    if op == "gte":
        return f"{field} >= {val}"
    if op == "gt":
        return f"{field} > {val}"
    if op == "contains":
        # cuDF string contains — case-sensitive, returns boolean Series.
        return f'{field}.str.contains("{val}")'
    return f"{field} == {_morpheus_value(val)}"


def _morpheus_value(v) -> str:
    """Format a Python value as a cuDF-expr literal."""
    if isinstance(v, str):
        return f'"{v}"'
    if isinstance(v, bool):
        return "True" if v else "False"
    return str(v)


def _yaml_inline_list(items: list[str]) -> str:
    """Render a flat list as a YAML inline list — '[a, b, c]'."""
    if not items:
        return ""
    rendered = ", ".join(items)
    return f"[{rendered}]"


def _window_to_seconds(window: str) -> int:
    """Translate '1h', '30m', '15m', '24h', '1d', '7d' to seconds."""
    table = {
        "1h": 3600, "30m": 1800, "15m": 900, "5m": 300,
        "1d": 86400, "24h": 86400, "7d": 604800,
    }
    return table.get(window, 3600)
